# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - rotating_base
      - shoulder_joint
      - elbow_joint
      - differential_joint
      - differential_rotation_joint
      - actuator_joint

    action_ns: follow_joint_trajectory
    default: true