controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      # ros__parameters: {}

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_fl_joint", "wheel_bl_joint"]
    right_wheel_names: ["wheel_fr_joint", "wheel_br_joint"]

    wheels_per_side: 2

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_radius: 0.115
    wheel_separation: 0.34
    
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    
    enable_odom_tf: true
    publish_rate: 50.0

    linear.x.min_velocity: -1.0
    linear.x.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_velocity: 1.0
